pull_request_rules:
   - name: label toto
      conditions:
        - label=tata
      actions:
        label:
          toggle:
            - 'toto'
    - name: label on queued
      conditions:
        - queue-position>=0
      actions:
        label:
          toggle:
            - 'queued'
