pull_request_rules:
  - name: dismiss reviews
      conditions: []
      actions:
        dismiss_reviews: {}
  
  - name: label on queued
      conditions:
        - queue-position>=0
      actions:
        label:
          toggle:
            - 'queued'
